"""Single source of configuration. One YAML file, atomic writes, hot-reload.

Atomic write (tmp + fsync + rename) is guard 4 from DESIGN.md: a power cut
mid-write can never leave a corrupt or half-written config, so flags like
`setup_complete` are either fully persisted or not at all.
"""
from __future__ import annotations

import os
import stat
import tempfile
from pathlib import Path

import yaml
from pydantic import BaseModel, Field

CONFIG_PATH = Path(os.environ.get("SKYLAPSE_CONFIG", "/etc/skylapse/config.yaml"))
IMAGE_ROOT = Path(os.environ.get("SKYLAPSE_IMAGES", "/var/lib/skylapse/images"))
RUN_DIR = Path(os.environ.get("SKYLAPSE_RUN", "/run/skylapse"))


class CaptureProfile(BaseModel):
    """Per-period capture settings. auto_exposure targets mean brightness.
    Timing is exposure + gap: the next capture starts gap_s after the
    previous one ENDS — true in auto and manual mode alike."""
    gap_s: int = 5
    auto_exposure: bool = True
    target_brightness: int = 90          # 0-255 mean of previous frame
    exposure_us: int = 20_000_000        # used when auto_exposure is False
    manual_safety_stop: bool = True      # manual mode only: pause capture on
                                         # daylight or repeated near-saturated
                                         # frames (protects a tracked sensor
                                         # from a forgotten dawn)
    max_exposure_us: int = 25_000_000    # AE clamp; keep < interval
    gain: int = 100
    max_gain: int = 300


class RawPolicy(BaseModel):
    mode: str = "off"                    # off | every_frame | every_nth | window
    every_nth: int = 10
    window_start: str = "22:00"          # local time, mode == "window"
    window_end: str = "02:00"
    keeper_buffer_frames: int = 3        # rolling RAM buffer for the keeper button


class TimelapseConfig(BaseModel):
    """Three user-facing knobs, sane defaults. Codec/format stay hard-baked."""
    auto_render: bool = True             # render at dawn automatically
    clip_seconds: int = 30               # target length; fps derived, clamped 12-60
    quality: str = "high"                # standard | high | max -> CRF 23/20/17


class NetworkConfig(BaseModel):
    mode: str = "auto"                   # auto | standalone | wifi_only
    hotspot_ssid: str = "Skylapse-Setup"
    hotspot_password: str = ""           # open by default; wizard can set one
    # Deadline for a timed access-point session, or 0 for "until turned off".
    # Persisted rather than held in memory so a power cut in the field cannot
    # quietly put the camera back on Wi-Fi while someone is still working on it.
    hotspot_until: float = 0.0


class DewHeaterConfig(BaseModel):
    """EXPERIMENTAL — unverified on hardware. Entirely inert unless
    experimental_enabled is explicitly set true: no I2C probe, no GPIO."""
    experimental_enabled: bool = False
    gpio_pin: int = 18                   # BCM numbering; PWM-capable pin
    on_margin_c: float = 2.0             # heat when within this of dewpoint
    off_margin_c: float = 4.0            # stop once clear by this much


class NotifyConfig(BaseModel):
    """Master switch + per-event toggles. Everything OFF by default."""
    enabled: bool = False
    ntfy_server: str = "https://ntfy.sh"
    ntfy_topic: str = ""                 # generated by the wizard, e.g. skylapse-a8x2k1
    events: dict[str, bool] = Field(default_factory=lambda: {
        "aurora": True, "storage_low": True,
        "camera_offline": True, "timelapse_ready": True, "safety_stop": True,
    })                                   # per-event toggles under the master switch


class LocationConfig(BaseModel):
    latitude: float = 0.0
    longitude: float = 0.0
    timezone: str = "UTC"


class CameraEntry(BaseModel):
    """Everything Skylapse remembers about one physical camera.

    Keyed in Config.cameras by a stable hardware id (ZWO serial/camera id,
    or model+sensor for Pi cams), so plugging in a known camera restores
    its profiles instantly and a new camera gets safe defaults once.
    """
    label: str = ""                      # user-friendly name ("Roof ASI224")
    driver: str = ""                     # "zwo" | "picam"
    model: str = ""
    first_seen: float = 0.0
    capture_schedule: str = "always"     # always | night_only. night_only skips
                                         # capture while the sun is up; every
                                         # other subsystem keeps running.
    day: CaptureProfile = Field(default_factory=lambda: CaptureProfile(
        gap_s=60, target_brightness=120, max_exposure_us=100_000, max_gain=50))
    night: CaptureProfile = Field(default_factory=CaptureProfile)
    raw: RawPolicy = Field(default_factory=RawPolicy)
    timelapse: TimelapseConfig = Field(default_factory=TimelapseConfig)
    overlay: bool = False                # burn timestamp/exposure into JPEGs
    # Colour multipliers for the JPEG path, green fixed at 1.0 as the
    # reference. Per camera because they are a property of the sensor and the
    # lens in front of it — the ASI676MC and the IMX477 have no business
    # sharing a number. Default 1.0/1.0 is exactly today's behaviour, so no
    # existing rig's output moves until its own sliders do.
    wb_r: float = Field(1.0, ge=0.1, le=8.0)
    wb_b: float = Field(1.0, ge=0.1, le=8.0)


class AuthConfig(BaseModel):
    """Optional single password. Off by default — see DESIGN.md.

    A camera on a LAN nobody else touches should not demand a login to look at
    the sky, so an empty hash means no protection at all rather than a locked
    device waiting for a password nobody set.
    """
    password_hash: str = ""              # empty = open, the default
    public_live_view: bool = False       # latest frame without login
    session_secret: str = ""             # generated when a password is first set


class UpdateConfig(BaseModel):
    """In-app updates. Skylapse only — never the OS."""
    channel: str = "release"              # release | dev (dev follows main)
    auto_check: bool = True               # daily check; applying is always manual


class Config(BaseModel):
    setup_complete: bool = False
    auth: AuthConfig = Field(default_factory=AuthConfig)
    location: LocationConfig = Field(default_factory=LocationConfig)
    network: NetworkConfig = Field(default_factory=NetworkConfig)
    notifications: NotifyConfig = Field(default_factory=NotifyConfig)
    dew_heater: DewHeaterConfig = Field(default_factory=DewHeaterConfig)
    updates: UpdateConfig = Field(default_factory=UpdateConfig)
    cameras: dict[str, CameraEntry] = Field(default_factory=dict)
    active_camera: str = ""              # camera_id; empty = auto (first detected)
    jpeg_quality: int = 92
    cleanup_free_gb: float = 2.0         # auto-delete oldest days below this

    def camera(self, camera_id: str) -> CameraEntry:
        """Fetch-or-create: unknown cameras get defaults and are persisted
        by the daemon on first sight."""
        if camera_id not in self.cameras:
            self.cameras[camera_id] = CameraEntry(first_seen=__import__("time").time())
        return self.cameras[camera_id]


def load() -> Config:
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH) as fh:
            return Config.model_validate(yaml.safe_load(fh) or {})
    return Config()


def write_run_file(name: str, text: str) -> None:
    """Write a status or command file into RUN_DIR, atomically.

    Three services share /run/skylapse and two of them do not run as root, so
    plain `write_text` on an existing file depends on who happens to own it.
    systemd re-applies RuntimeDirectory ownership *recursively* every time a
    unit using it starts — so netwatch starting (as root) rechowned the whole
    directory, and the daemon's next status write died with EACCES on a file it
    had written itself moments earlier. Measured on the rig at the first cold
    boot after netwatch was enabled: the daemon crashed 15s in and restarted.

    Creating a fresh file and renaming it over the old one needs write
    permission on the directory, which every one of these services has, and
    never on the file. It also means a reader can never catch a half-written
    status file, which was true before and only ever worked by luck.
    """
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=RUN_DIR, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(text)
        os.chmod(tmp, 0o644)          # mkstemp is 0600; these are read by peers
        os.replace(tmp, RUN_DIR / name)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def _inherit_ownership(tmp: str, target: Path) -> None:
    """Give `tmp` the mode and owner of `target`, so replacing it is invisible.

    Falls back to 0644 for a file being created, because the readers of this
    config are services that do not run as root.
    """
    try:
        st = os.stat(target)
    except FileNotFoundError:
        os.chmod(tmp, 0o644)
        return
    os.chmod(tmp, stat.S_IMODE(st.st_mode))
    try:
        os.chown(tmp, st.st_uid, st.st_gid)     # no-op for a non-root writer
    except (AttributeError, PermissionError, OSError):
        pass


def save(cfg: Config) -> None:
    """Atomic: write tmp in same dir, fsync, rename over the original.

    The replacement inherits the original's mode and owner. mkstemp creates
    0600 owned by whoever is writing, and netwatch writes this file as root —
    so on the rig an expiring hotspot session left /etc/skylapse/config.yaml
    root-only, and the api and daemon, which run as an ordinary user, could no
    longer read their own config. Every page returned 500 and capture stopped.
    An atomic write that silently changes who may read the file afterwards is
    not atomic in any sense that matters.
    """
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=CONFIG_PATH.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            yaml.safe_dump(cfg.model_dump(), fh, sort_keys=False)
            fh.flush()
            os.fsync(fh.fileno())
        _inherit_ownership(tmp, CONFIG_PATH)
        os.replace(tmp, CONFIG_PATH)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)
